development:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: url_shortener
  username: root
  password: root
test:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: url_shortener
  username: root
  password: root